baseURL = "http://fnooi.com/"
languageCode = "en-us"
title = "Felicia Huang's Website"
theme = "aafu"

[params]
    title = "Felicia N. Huang"
    author = "Felicia Huang"
    description = "Felicia Huang's Website"
    copyright = "Felicia Huang 2021"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Felicia N. Huang"
        tagline = "Ph.D., Research Fellow"
        location = "Singapore, Singapore"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/felicia-huang-a5392124/"
            title = "LinkedIn"		
        #[[params.social.list]]
            #icon = "fab fa-stack-overflow"
            #url = "#"
            #title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/fnhuang"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/FeliciaHuang16"
            title = "Twitter"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = "https://orcid.org/0000-0002-8700-8974"
            title = "Orcid"
        [[params.social.list]]
            icon = "ai ai-google-scholar"
            url = "https://scholar.google.com/citations?user=5pAqgfwAAAAJ&hl=en"
            title = "Google Scholar"
        #[[params.social.list]]
            #icon = "fab fa-researchgate"
            #url = "#"
            #title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    #[[params.showInAccordion]]
        #item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user fa-fw"
        description = "Felicia N. Huang is a research fellow at the Lee Kuan Yew Centre for Innovative Cities (LKYCIC). Prior to joining LKYCIC she received her Ph.D. from the Singapore Management Unviersity's School of Information Systems. Her research interests center on urban informatics, specifically its application on urban health and place identity."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase fa-fw"

        [[params.experience.list]]
            position = "Research Fellow"
            dates = "2018 - *Present*"
            company = "Lee Kuan Yew Centre for Innovative Cities"
            details = "Currently lead, conduct, and collaborate in several research projects that harness big data to help with urban planning. Guide and supervise research interns and assistants."
        [[params.experience.list]]
            position = "IT Analyst"
            dates = "2011 - 2012"
            company = "Singapore Telecommunications Ltd."
            details = "Assisted in building a website. Performed quality testing. Conducted code review."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap fa-fw"

        [[params.education.list]]
            degree = "Ph.D. in Information Systems"
            college = "Singapore Management University"
            dates = "2013 - 2018"
            thesis_title = "Exploring Offline Friendships on the Social Information Network"
            thesis_url = "/docs/feliciaThesis.pdf"
        [[params.education.list]]
            degree = "Visiting Scholar"
            college = "Center for Computational Analysis of Social Organizational Systems (CASOS), Carnegie Mellon University"
            dates = "2016 - 2017"
            thesis_title = ""
            thesis_url = "#"
        [[params.education.list]]
            degree = "B.Sc. in Information Systems"
            college = "Singapore Management University "
            dates = "2007 - 2011"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book fa-fw"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal", "publisher"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        # types = ["Journal Articles", "Proceedings", "Book Chapters"]
		types = ["Proceedings", "Book Chapters"]

        [[params.publication.list]]
            title = "Sensing Community Resilience from COVID-19 Using Social Media (accepted)"
            authors = "Felicia N. HUANG*, Kelly LIM, Evan SIDHI, Belinda YUEN"
            date = "2021"
            journal = "COVID –19 : Geospatial Information and Community Resilience"
			publisher = "Taylor and Francis Group"
            type = "Book Chapters"
			
		[[params.publication.list]]
            title = "Offline versus Online: A Meaningful Categorization of Ties for Retweet"
            authors = "Felicia NATALI*, Feida ZHU"
            date = "2018"
            journal = "10th International Conference on Social Informatics"
			publisher = "Springer"
            type = "Proceedings"
		
		[[params.publication.list]]
            title = "The Role of Different Tie Strength in Disseminating Different Topics on a Microblog"
            authors = "Felicia NATALI*,  Binxuan HUANG, Kathleen M. CARLEY, Feida ZHU"
            date = "2017"
            journal = "ASONAM '17: Advances in Social Networks Analysis and Mining"
			publisher = "ACM"
            type = "Proceedings"
		
		[[params.publication.list]]
            title = "A Comparison of Fundamental Network Formation Principles between Offline and Online Friends On Twitter"
            authors = "Felicia NATALI*, Feida ZHU"
            date = "2016"
            journal = "NetSci-X 2016: Advances in Network Science"
			publisher = "Springer"
            type = "Proceedings"
		
		[[params.publication.list]]
            title = "Extending the Network: The Influence of Offline Friendship on Twitter Network"
            authors = "Youngsoo KIM, Kyungsub CHOI, Felicia NATALI*"
            date = "2016"
            journal = "22nd Americas Conference on Information Systems (AMCIS 2016)"
			publisher = "Association for Information Systems (AIS)"
            type = "Proceedings"
		
		[[params.publication.list]]
            title = "Investigating the Influence of Offline Friendship on Twitter Networking Behaviors"
            authors = "Youngsoo KIM, Felicia NATALI*, Feida ZHU, and Ee-Peng LIM"
            date = "2016"
            journal = "2016 49th Hawaii International Conference on System Sciences (HICSS)"
			publisher = "IEEE"
            type = "Proceedings"


        #[[params.publication.list]]
            #title = "Offline versus Online: A Meaningful Categorization of Ties for Retweet"
            #authors = "Felicia NATALI, Feida ZHU"
            #date = "2018"
            #journal = "Journal of Field 52 (16), 9033-9044"
            #url = "#"
            #type = "Journal Articles"


    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram fa-fw"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs fa-fw"

        [[params.skill.list]]
            skill = "Python, R, Octave, Java, JavaScript, SQL, HTML / CSS, Bash, Hugo, Github"
		#[[params.skill.list]]
            #skill = "Skill 1, Skill 2"
            #skillrating = 90
        #[[params.skill.list]]
            #skill = "Skill 3"
            #skillrating = 80


    # Hobby section
    [params.hobby]
        title = "Languages"
        icon = "fas fa-comments fa-fw"

        [[params.hobby.list]]
            hobby = "Native Bahasa Indonesia"
		[[params.hobby.list]]
			hobby = "Fluent English (IELTS Band 8/CEFR C1)"
        [[params.hobby.list]]
            hobby = "Lower-Advanced Chinese (HSK 6/CEFR B2+)"
        [[params.hobby.list]]
            hobby = "Basic Russian (CEFR A2)"