Bagaimana memilih bahasa untuk dipelajari secara mendalam

Anda mungkin berpikir bahwa bahasa yang harus dipelajari secara mendalam adalah yang penggunanya paling banyak, atau negaranya lagi berkembang dengan pesat. Tetapi menurut pendapat saya, ini bisa menjadi pilihan yang salah. Mari kita lihat, pertimbangan apa saja yang penting untuk mengambil keputusan bahasa apa yang harus dipelajari secara mendalam. 

Belajar bahasa secara mendalam memerlukan investasi yang besar, terutama investasi waktu. Tentunya kalau Anda hanya ingin kemampuan untuk bercakap-cakap ringan saja, investasi waktu yang diperlukan tidak besar. Namun di artikel ini, saya tidak membahas mengenai pembelajaran bahasa seadanya saja, namun secara serius dan mendalam, seperti rata-rata orang jaman sekarang yang berkemampuan berbahasa inggris dengan sangat fasih. Perlukah kita mempelajari bahasa lain selain bahasa inggris secara mendalam, dan jika ya, pertimbangan apa saja yang harus menjadi basis dari pilihan bahasa? Anda mungkin berpikir bahwa bahasa yang harus dipelajari secara mendalam adalah yang penggunanya paling banyak, atau negaranya lagi berkembang dengan pesat. Tetapi menurut pendapat saya, ini bisa menjadi pilihan yang salah. Saya juga membuat kesalahan tersebut, dan tidak ingin Anda membuat kesalahan yang sama. Mari kita lihat, poin penting di bawah ini yang seharusnya dipertimbangkan. 

# Manfaat ekonomi hanya positif, jika bidang pekerjaan memang membutuhkan bahasa tersebut. 
Banyak artikel-artikel menuliskan bahwa jika bisa berbahasa X dan Y, kesempatan kerja akan lebih besar. Misalkan saja, di jaman dahulu, kalau mahir berbahasa inggris, asumsinya adalah tawaran pekerjaan akan lebih banyak. Benarkah? Coba pikirkan lagi. Apakah presiden Jokowi inggrisnya mahir? Apakah presiden Xi, bahasa inggrisnya mahir? President Putin, inggrisnya mahirkah? Saya rasa tidak. Contohnya lagi, saat saya bekerja di Singtel, saya harus berkomunikasi dengan insinyur perangkat lunak dari Cina. Bahasa inggris mereka seadanya saja. 

Sama halnya dengan bahasa mandarin. Jaman sekarang, yang lagi trendi, adalah bahasa mandarin. Banyak yang bilang, bisa bahasa mandarin, akan lebih gampang mencari kerja. Coba pikirkan lagi. Teman saya yang tinggal di Indonesia, namun orangtuanya dari cina, dan dia lulus dari universitas Tsinghua, berkata bahwa dengan kemampuan bahasa mandarinnya yang sangat mahir, kemampuan cari kerja di Indonesia tidak menjadi lebih besar secara signifikan. Gaji juga tidak menjadi lebih tinggi secara signifikan. Semua kembali kepada keahlian apa yang diperlukan perusahaan, dan apakah Anda memiliki keahlian tersebut. 

Tentunya, jika Anda memang bekerja sebagai penerjemah, atau pekerjaan lainnya di mana bahasa asing memang sangat terpakai, kemampuan berbahasa sangatlah penting. Tetapi jika tidak, kemampuan berbahasa itu hanyalah sampingan. Lebih baik waktu Anda dihabiskan untuk mengembangkan keahlian bidang Anda. Misalnya Anda seorang insinyur, jadilah seorang insinyur yang sangat mahir. Dengan begini kemungkinannya lebih besar nilai Anda naik di mata perusahaan dan gaji juga dinaikkan. 

Anda mungkin akan beragumen, tetapi lulusan luar negeri lebih sering sukses mendapat kerja! Dan ini akan saya bahas di poin berikutnya. 

# Yang harus dilihat, bukan seberapa berkembang suatu negara, tetapi seberapa besar kesempatan untuk tinggal, dan sekolah di negara tersebut dan seberapa bagus potensi untuk bekerja dengan perusahaan dari negara tersebut. 
Ya benar, lulusan luar negeri sering lebih sukses mendapatkan kerjaan, dan alasannya bukan semata-mata bahasa. Nomor satu, universitas luar negeri dianggap lebih berkualitas. Nomor dua, perusahaan negara asing banyak yang mengadakan kerja sama dengan perusahaan lokal, atau bahkan mendirikan anak perusahaan di negara kita. Tentunya perusahaan-perusahaan lokal ini akan memilih lulusan dari luar negeri karena bisa menjadi jembatan antara perusahaan asing dan perusahaan kita.  Ini tidak sesimpel kemampuan berbahasa saja. Perusahaan yang butuh seseorang yang mahir berbahasa inggris, belum tentu bisa diyakinkan hanya dengan melihat hasil tes inggris seperti IELTS/TOEFL. Perusahaan cina yang butuh orang mahir mandarin, belum tentu lega memberikan pekerjaan kepada yang nilai HSK-nya tinggi saja. Mereka akan memilih lulusan negara mereka, karena adanya pengalaman tinggal dan sekolah di negara mereka di mana bahasa mereka digunakan dengan sangat intensif. 

Maka dari itu, salah satu hal yang harus dipertimbangkan adalah seberapa besar kesempatan untuk tinggal, dan sekolah di negara tersebut. Setelah itu, seberapa bagus potensi untuk bekerja dengan perusahaan dari negara tersebut, baik yang di luar negeri, atau di dalam negeri. Beberapa contoh pertanyaan yang bisa ditanyakan ke diri-sendiri adalah: Apakah perusahaan dari negara tersebut sering mempekerjakan orang asing? Apakah koneksi bisnis negara tersebut dengan negara kita mulus? Apakah mereka memberikan beasiswa untuk orang asing? 

Dan ini tentunya membawa kita kepada poin berikut. 

# Yang harus dilihat bukan seberapa banyak penggunanya, tetapi di mana anda tinggal dan bekerja.
Ibu saya waktu kecil suka menasehati, "Bahasa inggris bahasa internasional. Kalau dipelajari nanti bisa sering terpakai". Jujur, saya jarang sekali memakai bahasa inggris untuk berkomunikasi, sampai saya sekolah ke Singapur. Sebenarnya, jika Anda tidak tinggal di negara yang menggunakan bahasa tersebut, kemungkinan Anda bisa bertemu dan berkomunikasi dengan penduduk dari negara asing juga tidak banyak. Sedangkan kalau sekedar untuk berkomunikasi dengan orang asing lewat sosial media, belajar seadanya sudah bisa berkomunikasi, tidak perlu sampai mendalam. 

# Yang harus dilihat bukan etnis, tetapi ada tidaknya sanak keluarga dekat dari pengguna bahasa tersebut. 
Saya dahulu sering berpikir, saya etnis Cina, harusnya bisa bahasa Cina dong! Tetapi begitu sudah dipelajari sampai mahir, malahan bingung, dengan siapa saya akan berbicara? Orang tua saya tahunya dialek Hokkien, dan bahasa Indonesia. 

Hal lain yang terpikirkan adalah, mungkin bahasa tersebut bisa diteruskan ke anak cucu. Di sini lagi, peran sanak keluarga terdekat sangat penting. Saat saya berdiskusi dengan calon suami, kalau anak ke depannya akan diajarkan bahasa apa, saya terus terang bingung. Diajarkan 4 bahasa? Mungkin, tetapi tetap harus ada bahasa ibu yang diutamakan. Bahasa apa yang harus saya pilih? 

Bahasa inggris? Kami merasa anak harus bisa bahasa lain selain bahasa inggris, karena kami bukan orang inggris. 

Bahasa cina? Saya sudah lulus HSK6 yang terhitung seperti lulus Mandarin O-level di Singapur dengan nilai B4. Meskipun bahasa cina saya terhitung cukup mahir, tetapi tetap bukan bahasa ibu. Saya masih sering membuat kesalahan-kesalahan kecil. Saya juga tidak pernah tinggal di negara yang secara intensif menggunakan mandarin. Kalau di singapur, kemampuan seadanya saja sudah cukup untuk berkomunikasi. Saya sekarang sudah bisa pesan makanan, berbicara dengan tukang taksi, bahkan mewawancarai orang tua di singapur untuk bahan riset. Namun, kalau berbicara yang agak panjang dan sedikit ilmiah, misalkan menjelaskan bagaimana hujan turun dari langit ke anak, atau menjelaskan isi berita, kemampuan saya hanya sebatas membaca. Dalam berbicara masih sangat belum terbiasa dan kagok, karena jarang digunakan. Bagaimana menjadikan bahasa cina bahasa ibu kalau begini? Belum lagi anak tidak bisa berbicara dengan orang tua saya nantinya. 

Bahasa indonesia? Nanti dia pulang ke kampung ibunya, yang sudah Singapur, dia tidak bisa berbicara bahasa Mandarin, padahal salah satu etnis di paspor si anak akan Cina - mengikuti etnis di KTP saya. Belom lagi, anak yang dari kecil belajar bahasa cepat, difokuskan untuk menyerap bahasa Indonesia yang terhitung gampang, apa tidak sayang? Kalau nanti sudah agak besar baru belajar bahasa Indonesia, juga belum telat. Bahasa Indonesia adalah bahasa yang terhitung gampang, bukan hanya menurut saya, tetapi secara umum. Kalau tidak percaya tanya saja bule-bule yang pernah belajar bahasa Indonesia. 

Jadilah ujung-ujungnya kita putuskan bahasa ibu anak yang utama, bahasa Rusia saja. Karena anak nantinya masih punya kakek nenek, paman dan bibi yang bisa berbicara dengan dia. Ayahnya juga terbiasa berbicara bahasa rusia, jadi dibandingkan bahasa cina, bahasa rusia akan lebih mudah untuk menjadi bahasa ibu si anak. Di sisi lain, saya belajar bahasa terhitung sangat cepat. Jadi, bagi saya bukan hal yang berat sekali untuk belajar bahasa rusia demi mendukung lingkungan yang kondusif bagi anak berbicara rusia. 

Bagaimana dengan bahasa indonesia dan mandarin? Saya akan tetap berbicara bahasa mandarin dan indonesia dengan anak, namun seadanya dahulu. Fokusnya akan ke dua bahasa dahulu, yaitu rusia dan inggris. Sebenernya saya ingin anak saya mahir mandarin. Tetapi bisa jadi nanti mahirnya akan bahasa indonesia, karena ibu ayah saya berbicara bahasa indonesia. Ujung-ujungnya sanak keluargalah yang menentukan apakah bahasa bisa dengan mulus diteruskan ke anak. 

Jika, tidak bisa berbicara dengan keluarga, tidak bisa diteruskan ke anak, mungkin belajar bahasa bisa membantu mencari teman? Misalnya, mencari teman dari Cina, Jepang, atau Korea mungkin? Ini saya akan bahas di topik berikutnya. 

# Jika alasannya karena ingin mempunyai banyak teman dengan orang dari negara tersebut, sebaiknya dipikirkan secara lebih bijak. 
Di indonesia, ada fenomena terbaru, namanya [Fiki Naki]. Bang Fiki terkenal karena bisa banyak bahasa, terutama bahasa rusia dan inggris. Terus terang, saya gereget sekali liat bang Fiki, karena dimana-mana diberitakan "mahir" dan "fasih" berbicara rusia. Padahal videonya dari tahun lalu sampai sekarang, bahasa rusianya cuma beberapa patah kalimat yang diulang-ulang saja. Begitu percakapan sedikit melenceng, sudah bingunglah si Fiki, atau kalau tidak tata bahasanya sudah salah. Sebenernya Fiki Naki itu kemampuan berbahasa rusianya tidak lewat A2 yang artinya "dasar". Belum tingkat "fasih". Tingkat A2 itu sudah bisa bercakap-cakap ringan dengan orang luar, asal percaya diri dan terbiasa. Itu mengapa kalau di kebanyakan negara Eropa, batas minimum kemampuan berbahasa untuk menjadi warga negara hanyalah A2 saja. Contohnya lagi, wanita Swedia ini menikah dengan orang Cina dan bahasa mandarinnya hanyalah setingkat HSK4 (A2), tetapi dia bisa berkomunikasi Mandarin tanpa masalah dengan suami dan anaknya. Jadi kalau tujuannya mencari teman saja, jangan terlalu menghabiskan waktu mempelajari secara mendalam. Seadanya saja sudah cukup. 

Hal kedua soal berteman adalah, kemampuan bahasa bagus bukan berarti berteman akan menjadi gampang. Banyak sekali orang Indonesia ke Amerika sekolah, ujung-ujungnya bertemannya dengan orang Indonesia lagi. Banyak yang bilang, orang Amerika ramah di luar, tetapi sebenarnya tetap saja membangun dinding dalam pertemanan dekat dengan orang asing. Kenalan sih ya bisa dari manca negara, namun pertemanan perlu rasa kepercayaan yang erat. Jadi sangat naif kalau berpikir, kita bisa berbahasa mereka, dan mereka lantas senang menjadikan kita teman. Itu kembali lagi ke pribadi kita sendiri, apakah memang santai dan mudah berteman. Ini juga tergantung kepada pandangan orang negara tersebut terhadap orang negara kita: positif, atau negatif. 

# Sangat berguna, tetapi sering diabaikan: Mendalami agama (bagi yang religius, tentunya).
Kita sering berpikir, bahwa belajar bahasa hanya untuk mendalami agama, tidak terlalu penting, karena teks yang ada sudah banyak diterjemahkan. Contohnya Quran diterjemahkan dari Arab ke bahasa Asia lainnya. Saya dulu juga berpikir begitu. Namun, belakangan ini di saat mengikuti kelas terjemahan untuk teks Buddhisme Tibet yang judulnya "Kereta Besar" saya baru sadar bahwa banyak sekali kata-kata Tibet yang dalam terjemahan Inggris tidak bisa disampaikan secara detil nuansa-nuansanya. Nuansa-nuansa ini bisa membawa pengertian yang lebih mendalam dan mengetuk hati. Hal yang sama terjadi di saat saya membaca sutra Cina di saat saya belum menguasai dan sudah menguasai bahasa Mandarin, misalnya saja "Sutra Prajnaparamita". Pemahamannya sama, namun intuisi dan perasaan yang didapat bisa sangat berbeda. Jadi, jika Anda orangnya religius, belajar bahasa untuk mendalami agama tidak akan sia-sia. 

[longchenpa]
 
# Jika sekedar hobi atau talenta, tidak perlu didalami, kecuali Anda jadikan sebuah profesi.  
Bagaimana kalau hobi? Atau talenta? Menurut saya, kalau sekedar hobi, atau talenta, tidak perlu dipelajari secara mendalam, kecuali ingin dijadikan profesi. Saya bisa dihitung sangat bertalenta di mandarin. Dulu, saat saya ambil kelas mendasar mandarin di Universitas Manajemen Singapur, saya dan salah satu anak malaysia dipanggil guru sesudah kelas. Kita ditanya, apakah orang tua berbicara bahasa mandarin ke kami, karena kelas ini tidak boleh untuk anak yang bahasa ibunya mandarin. Padahal, di kelas itu, benar-benar pertama kalinya saya belajar pinyin. Lalu di saat saya ke Cina belajar, guru selalu tanya apakah orang tua saya dari Cina, karena saya belajar sangat cepat dibandingkan murid-murid lainnya, dan pelafalan kata saya bagus. Namun ujung-ujungnya bahasa mandarin saya juga tidak terlalu terpakai, dan jerih payah dan waktu yang terbuang untuk mempelajari secara mendalam rasanya sia-sia saja. Jadi ini membawa kita kepada poin terakhir.

# Kesimpulan: jika waktu bisa diulang, bahasa apa yang akan saya pelajari? 
Kalau waktu bisa diulang, akankah saya tetap belajar bahasa mandarin? Pasti. Tapi tidak akan sampai mendalam sekali. Mungkin sampai HSK4 saja. Seadanya saja. Tidak perlu sampai ke Cina dua kali. Sekali saja cukup. Tidak perlu sampai bisa memahami film Cina tanpa teks inggris. Asal bisa pesan makanan di kantin Singapura saja cukup. Kalau tujuan saya hanya seperti ini, umur 20 saja pasti sudah tercapi gol tersebut, dan waktu yang tersisa bisa saya gunakan belajar bahasa Rusia. Seandainya saya sudah belajar bahasa rusia sedari dulu, sekarang pasti bahasa rusia saya sudah cukup mahir. Sayangnya, bermimpi pun tidak, bahwa calon suami saya akan orang Rusia. Ujung-ujungnya, jika masih ada waktu, mungkin akan saya pelajari bahasa Tibet secara serius, karena itu akan mendukung pelatihan spiritual saya. 

Tapi nasi sudah menjadi bubur. Saya tidak menyesal, karena bagaimanapun saya cukup menikmati proses belajar mandarin. Saat ini saya ingin mencoba memonetisasi kemampuan berbahasa saya. Dulu di saat belajar doktor, saya pernah menjadi penerjemah bahasa Mandarin ke bahasa Inggris. Terjemahan saya bisa dilihat di CV. Lumayan juga, satu artikel bisa mendapat 100-200 USD. Namun jaman sekarang menjadi penejermah Mandarin makin kompetitif saja. Apalagi translator sekarang menggunakan bantuan alat Artificial Intelligence, seperti MATECAT untuk membantu translasi. Makin banyak saja yang bisa melakukan pekerjaan ini. Maka itu, susah sekali sekarang mendapat pekerjaan sampingan sebagai penejermah mandarin. Semoga artikel ini memberikan info-info dan pandangan-pandangan menarik untuk Anda, dan tentunya jika ada yang berminat untuk mencari penejermah Mandarin bisa menghubungi saya. 